-- CREATE TYPE RoleEnum AS ENUM ('ROLE_USER', 'ROLE_ADMIN');
INSERT INTO public.roles (name) VALUES ('ROLE_USER'),('ROLE_MODERATOR'),('ROLE_ADMIN');
INSERT INTO public.type_document (type) VALUES ('NOTE'),('REPORT'),('PRESENTATION'),('ARTICLE'),('DEFAULT_DOCUMENT');